framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        #failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: jobs
                        type: topic
                    queues:
                        '%env(CONSUMER_QUEUE_NAME)%':
                            binding_keys: '%env(json:CONSUMER_BINDING_KEYS)%'
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 60000

            # To save failed messages to the database
            #failed: 'doctrine://default?queue_name=failed'
            # To save failed messages to RabbitMQ
            # failed: '%env(MESSENGER_TRANSPORT_DSN)%/failed'

        routing:
            App\Example\Message\Ping: async
            App\Message\GenericMessage: async
